seed: 1
cache: false # caching available only for encoded datasets

# Training
multinode: False
batch_size: 512  # 96  # 32
eval_size: 512  # 96  # 32  # 1024
num_workers: 64  # 8
lr: 0.0003
lr_schedule: "cosine"
weight_decay: 0.00001
total_steps: 30000000
test_steps: 10
warmup_steps: 5000
save_interval: 1000
viz_interval: 2000
log_interval: 100

# Data
data_path: "/raid/moving_mnist_long_1"
eval_seq_len_1: 10
eval_seq_len_2: 10
seq_len: 10  # Recurrent steps
image_reps: 1
image_size: 64
channels: 1
resize: [256, 256, 1]

num_shards: null
rng_keys: ["dropout", "sample"]
batch_keys: ["video", "actions"]

# Model
model: "pf_convS5_noVQ"

loss_weight: 1  # 0.5

encoder: # encoder / decoder are mirrored, with decoder depths reversed
  depths: [64, 128, 256] # 64x64 to 16x16
  blocks: 1 #blocks doesn't do anything here

decoder: # encoder / decoder are mirrored, with decoder depths reversed
  depths: [64, 128, 256] # 16x16 to 64x64
  blocks: 1

d_model: 24  # 256

# Sequence Model
seq_model:
  n_layers: 2
  layer_activation: "gelu"
  dropout: 0.0
  use_norm: True
  prenorm: True  # False
  per_layer_skip: True
  num_groups: 1  # 32
  squeeze_excite: False
  skip_connections: False

# SSM
ssm:
  ssm_size: 48
  blocks: 1
  clip_eigs: True
  B_kernel_size: 3
  C_kernel_size: 3
  D_kernel_size: 3
  dt_min: 0.001
  dt_max: 0.1
  C_D_config: "resnet"


latent_height: 64  # 64
latent_width: 64  # 64

n_cond: 1
drop_loss_rate: 0.0

causal_masking: False

# Actions
use_actions: False
action_dim: 1
action_embed_dim: 1
dropout_actions: False
action_dropout_rate: 0.0
action_mask_id: -1

# Sampling
open_loop_ctx: 30

open_loop_ctx_1: 30
action_conditioned_1: False
open_loop_ctx_2: 30
action_conditioned_2: False

